# Generated by Django 4.1.1 on 2022-11-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='categories')),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('page', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('pdf', models.FileField(upload_to='pdf')),
                ('recommanded_books', models.BooleanField(default=False)),
                ('bussiness_books', models.BooleanField(default=False)),
                ('fiction_books', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(related_name='book', to='Crudapp.category')),
            ],
        ),
    ]
